### ISSUE TITLE
Content overflow on login screen

### ISSUE THREAD

**Issue by derisen** [Azure-Samples/ms-identity-javascript-nodejs-desktop#10]
When creating a new browserwindow object in electron the login page content has an overflow, showing a scrollbar. The scrollbar only moves a tiny amount up and down. Would be better to remove it.

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
This behavior is present in the example app ms-identity-javascript-nodejs-desktop-main

### Any log messages given by the failure
>

### Expected/desired behavior
New browserwindow object opens login page without scrollbars (overflow hidden)

### OS and version?
Chrome, Other

### Versions
2.14.1

### Mention any other details that might be useful

```
ipcMain.handle('login', async () => {

  // create a new electron window
  const authWindow = new BrowserWindow({
    width: 800,
    height: 600,
    show: true,
    frame: false,
    webPreferences: {
      nodeIntegration: false,
    },
  });
  // get token
  const tokenRequest = {
    scopes: [
      'User.Read',
      'Tasks.Read',
      'Group.ReadWrite.All',
      'Directory.ReadWrite.All',
    ],
  };
  const token = await authProvider.getToken(authWindow, tokenRequest);

  // close the auth window
  authWindow.destroy();

  return 'succeeded';
});
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

cc @rbWies

**Comment by rbWies** [comment]
Thank you for closing the issue in the other repository and re-creating here!

**Comment by capc0** [comment]
we have encountered the same issue.

Sometimes the existence of the vertical scrollbar also causes a horizontal scollbar to appear too.

**Comment by capc0** [comment]
This is not fixed. But I guess it is not even part of the source code and is controlled by the loaded HTML itself.

![image](https://user-images.githubusercontent.com/27284008/196775543-7aa0f61a-bce3-4193-b085-2ad80a55ee7c.png)

**Comment by salman90** [comment]
Hi @capc0, This is the default behavior for the account selection screen, and we can't do much about it. You can [customize the user interface](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding) for the page, but you can't change the CSS.
