### ISSUE TITLE
Link to Electron with React implementation not working

### ISSUE THREAD

**Issue by CasparGalen** [Azure-Samples/ms-identity-javascript-nodejs-desktop#14]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Go to https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop
>Go to the section "ℹ️ Looking for an Electron with React implementation? See: [ElectronReactTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronReactTestApp)" in the README. 
>Click on ElectronReactTestApp and the link will lead to a 404 page.

### Expected/desired behavior
>A link to an Electron React App example

### OS and version?
>Any

### Versions
>latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
@Caspar-Progius  Thanks for flagging this!
