### ISSUE TITLE
No code found in URL

### ISSUE THREAD

**Issue by cssuh** [Azure-Samples/ms-identity-javascript-nodejs-desktop#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow README steps 

### Any log messages given by the failure
>(node:9112) UnhandledPromiseRejectionWarning: Error: No code found in URL
    at Function.<anonymous> (C:\Users\chsuh\Documents\work\repos\ms-identity-javascript-nodejs-desktop\App\CustomProtocolListener.js:41:18)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:9112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
### Expected/desired behavior
> I want to use the Sign In but it returns this error

### OS and version?
> Mac OS 12.4 (I have tried on Windows 11 as well)

### Versions
> {
  "name": "electron-test-app",
  "version": "1.0.0",
  "description": "A sample Electron application that uses msal-node to acquire tokens",
  "main": "Main.js",
  "scripts": {
    "start": "electron App/Main.js"
  },
  "keywords": [
    "msal-node",
    "electron",
    "javascript"
  ],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel": "^6.23.0",
    "electron": "^18.2.3",
    "webpack": "^5.6.0"
  },
  "dependencies": {
    "@azure/msal-node": "^1.0.0",
    "axios": "^0.21.4",
    "bootstrap": "^4.5.3",
    "dotenv": "^8.2.0",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1"
  }
}

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cssuh** [comment]
I got it working, I had the wrong value in my redirect_uri

**Comment by salman90** [comment]
@cssuh That's good news. I was just going to ask you to share your authConfig.js file. Let us know if you have any additional questions.
